import os
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph
from reportlab.platypus import Spacer

from app.services.summary_cache_service import SummaryCacheService


class PDFReportService:

    def __init__(self):

        self.summary_cache = SummaryCacheService()

        self.base_folder = "reports"

        os.makedirs(
            self.base_folder,
            exist_ok=True
        )

    def generate_pdf(
        self,
        domain: str,
        source_file: str
    ):

        cached_summary = self.summary_cache.load_summary(
            domain=domain,
            source_file=source_file
        )

        if cached_summary is None:
            raise Exception("Summary not found.")

        summary = cached_summary["summary"]

        domain_folder = os.path.join(
            self.base_folder,
            domain
        )

        os.makedirs(
            domain_folder,
            exist_ok=True
        )

        pdf_name = source_file.replace(
            ".pdf",
            "_summary.pdf"
        )

        pdf_path = os.path.join(
            domain_folder,
            pdf_name
        )

        document = SimpleDocTemplate(
            pdf_path
        )

        styles = getSampleStyleSheet()

        story = []

        story.append(
            Paragraph(
                "<b><font size=20>DOCUMENT SUMMARY</font></b>",
                styles["Title"]
            )
        )

        story.append(
            Spacer(
                1,
                20
            )
        )

        story.append(
            Paragraph(
                f"<b>Document:</b> {source_file}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y %H:%M')}",
                styles["Normal"]
            )
        )

        story.append(
            Spacer(
                1,
                20
            )
        )

        story.append(
            Paragraph(
                summary.replace("\n", "<br/>"),
                styles["BodyText"]
            )
        )

        story.append(
            Spacer(
                1,
                30
            )
        )

        story.append(
            Paragraph(
                "<b>Generated by Enterprise Multi-Domain Chatbot</b>",
                styles["Italic"]
            )
        )

        document.build(
            story
        )

        return pdf_path